"""Tests for ``llm_wiki_kit.schedule.launchd``.

Covers the four mandated cases from plan step 4 in
``docs/specs/wiki-schedule/plan.md``:

1. ``render_artifact()`` golden-string assertions for each cadence kind
   (daily / weekly / monthly / quarterly). The weekly golden string for
   ``TUE 18:00`` also pins spec CT-2's ``Weekday=2 Hour=18 Minute=0``
   encoding.
2. For a quarterly cadence, the rendered plist's ``StartCalendarInterval``
   is a four-element array of dicts whose ``Month`` keys are
   ``(1, 4, 7, 10)``. Pins that the emitter hands the full
   ``to_launchd_calendar_interval(...)`` list to ``plistlib``, not just
   ``intervals[0]``.
3. The argv-block contents pin ``wiki run --exec <op>`` shape in
   ``ProgramArguments``.
4. ``inspect()`` returns each of the four ``InspectResult`` states given
   fixture ``launchctl print`` outputs (mocked via subprocess monkeypatch
   of the ``llm_wiki_kit.schedule.launchd`` module, per the style
   convention in ``schedule/_emitter.py``).

Integration test (``@pytest.mark.slow``, Darwin-only) lives in
``tests/integration/test_schedule_launchd_macos.py``.
"""

from __future__ import annotations

import plistlib
import subprocess
from pathlib import Path

import pytest

from llm_wiki_kit.schedule.dsl import ResolvedCadence
from llm_wiki_kit.schedule.launchd import LaunchdEmitter

# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------

VAULT_ROOT = Path("/Users/user/vault")
VAULT_ID = "abcdef123456"
EXEC_CMD = ["/usr/local/bin/wiki", "run", "--exec", "test-op"]

# A stable artifact path fixture used by inspect() tests.
_ARTIFACT_NAME = f"com.llm-wiki-kit.{VAULT_ID}.test-op.plist"


@pytest.fixture
def emitter() -> LaunchdEmitter:
    return LaunchdEmitter()


@pytest.fixture
def artifact_file(tmp_path: Path) -> Path:
    """Create a real (empty) plist file so ``artifact_path.exists()`` is True."""
    p = tmp_path / _ARTIFACT_NAME
    p.touch()
    return p


# ---------------------------------------------------------------------------
# 1. Golden-string assertions per cadence kind
# ---------------------------------------------------------------------------

# The golden strings below were generated by running the emitter against the
# same inputs and capturing the exact bytes. plistlib uses sort_keys=True by
# default, so keys appear alphabetically inside each <dict>.

_DAILY_GOLDEN = (
    b'<?xml version="1.0" encoding="UTF-8"?>\n'
    b'<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"'
    b' "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    b'<plist version="1.0">\n'
    b"<dict>\n"
    b"\t<key>Label</key>\n"
    b"\t<string>com.llm-wiki-kit.abcdef123456.daily-op</string>\n"
    b"\t<key>ProgramArguments</key>\n"
    b"\t<array>\n"
    b"\t\t<string>/usr/local/bin/wiki</string>\n"
    b"\t\t<string>run</string>\n"
    b"\t\t<string>--exec</string>\n"
    b"\t\t<string>daily-op</string>\n"
    b"\t</array>\n"
    b"\t<key>RunAtLoad</key>\n"
    b"\t<false/>\n"
    b"\t<key>StandardErrorPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stderr.log</string>\n"
    b"\t<key>StandardOutPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stdout.log</string>\n"
    b"\t<key>StartCalendarInterval</key>\n"
    b"\t<array>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>7</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t</dict>\n"
    b"\t</array>\n"
    b"\t<key>WorkingDirectory</key>\n"
    b"\t<string>/Users/user/vault</string>\n"
    b"</dict>\n"
    b"</plist>\n"
)


def test_render_daily_golden(emitter: LaunchdEmitter) -> None:
    """Daily cadence produces the exact plist bytes pinned above."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    result = emitter.render_artifact(
        operation="daily-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=["/usr/local/bin/wiki", "run", "--exec", "daily-op"],
    )
    assert result == _DAILY_GOLDEN


# spec CT-2: TUE 18:00 → Weekday=2 Hour=18 Minute=0 (Sunday=0…Saturday=6).
_WEEKLY_TUE_1800_GOLDEN = (
    b'<?xml version="1.0" encoding="UTF-8"?>\n'
    b'<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"'
    b' "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    b'<plist version="1.0">\n'
    b"<dict>\n"
    b"\t<key>Label</key>\n"
    b"\t<string>com.llm-wiki-kit.abcdef123456.weekly-digest</string>\n"
    b"\t<key>ProgramArguments</key>\n"
    b"\t<array>\n"
    b"\t\t<string>/usr/local/bin/wiki</string>\n"
    b"\t\t<string>run</string>\n"
    b"\t\t<string>--exec</string>\n"
    b"\t\t<string>weekly-digest</string>\n"
    b"\t</array>\n"
    b"\t<key>RunAtLoad</key>\n"
    b"\t<false/>\n"
    b"\t<key>StandardErrorPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stderr.log</string>\n"
    b"\t<key>StandardOutPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stdout.log</string>\n"
    b"\t<key>StartCalendarInterval</key>\n"
    b"\t<array>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>18</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t\t<key>Weekday</key>\n"
    b"\t\t\t<integer>2</integer>\n"
    b"\t\t</dict>\n"
    b"\t</array>\n"
    b"\t<key>WorkingDirectory</key>\n"
    b"\t<string>/Users/user/vault</string>\n"
    b"</dict>\n"
    b"</plist>\n"
)


def test_render_weekly_tue_1800_golden(emitter: LaunchdEmitter) -> None:
    """Weekly TUE 18:00 produces plist with Weekday=2 Hour=18 Minute=0 (spec CT-2)."""
    cadence = ResolvedCadence(period="weekly", hour=18, minute=0, day_of_week=2)
    result = emitter.render_artifact(
        operation="weekly-digest",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=["/usr/local/bin/wiki", "run", "--exec", "weekly-digest"],
    )
    assert result == _WEEKLY_TUE_1800_GOLDEN


_MONTHLY_DAY5_0900_GOLDEN = (
    b'<?xml version="1.0" encoding="UTF-8"?>\n'
    b'<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"'
    b' "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    b'<plist version="1.0">\n'
    b"<dict>\n"
    b"\t<key>Label</key>\n"
    b"\t<string>com.llm-wiki-kit.abcdef123456.monthly-op</string>\n"
    b"\t<key>ProgramArguments</key>\n"
    b"\t<array>\n"
    b"\t\t<string>/usr/local/bin/wiki</string>\n"
    b"\t\t<string>run</string>\n"
    b"\t\t<string>--exec</string>\n"
    b"\t\t<string>monthly-op</string>\n"
    b"\t</array>\n"
    b"\t<key>RunAtLoad</key>\n"
    b"\t<false/>\n"
    b"\t<key>StandardErrorPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stderr.log</string>\n"
    b"\t<key>StandardOutPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stdout.log</string>\n"
    b"\t<key>StartCalendarInterval</key>\n"
    b"\t<array>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Day</key>\n"
    b"\t\t\t<integer>5</integer>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>9</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t</dict>\n"
    b"\t</array>\n"
    b"\t<key>WorkingDirectory</key>\n"
    b"\t<string>/Users/user/vault</string>\n"
    b"</dict>\n"
    b"</plist>\n"
)


def test_render_monthly_golden(emitter: LaunchdEmitter) -> None:
    """Monthly day-5 cadence produces the exact plist bytes pinned above."""
    cadence = ResolvedCadence(period="monthly", hour=9, minute=0, day_of_month=5)
    result = emitter.render_artifact(
        operation="monthly-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=["/usr/local/bin/wiki", "run", "--exec", "monthly-op"],
    )
    assert result == _MONTHLY_DAY5_0900_GOLDEN


_QUARTERLY_DAY1_0900_GOLDEN = (
    b'<?xml version="1.0" encoding="UTF-8"?>\n'
    b'<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"'
    b' "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    b'<plist version="1.0">\n'
    b"<dict>\n"
    b"\t<key>Label</key>\n"
    b"\t<string>com.llm-wiki-kit.abcdef123456.quarterly-op</string>\n"
    b"\t<key>ProgramArguments</key>\n"
    b"\t<array>\n"
    b"\t\t<string>/usr/local/bin/wiki</string>\n"
    b"\t\t<string>run</string>\n"
    b"\t\t<string>--exec</string>\n"
    b"\t\t<string>quarterly-op</string>\n"
    b"\t</array>\n"
    b"\t<key>RunAtLoad</key>\n"
    b"\t<false/>\n"
    b"\t<key>StandardErrorPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stderr.log</string>\n"
    b"\t<key>StandardOutPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stdout.log</string>\n"
    b"\t<key>StartCalendarInterval</key>\n"
    b"\t<array>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Day</key>\n"
    b"\t\t\t<integer>1</integer>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>9</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t\t<key>Month</key>\n"
    b"\t\t\t<integer>1</integer>\n"
    b"\t\t</dict>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Day</key>\n"
    b"\t\t\t<integer>1</integer>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>9</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t\t<key>Month</key>\n"
    b"\t\t\t<integer>4</integer>\n"
    b"\t\t</dict>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Day</key>\n"
    b"\t\t\t<integer>1</integer>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>9</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t\t<key>Month</key>\n"
    b"\t\t\t<integer>7</integer>\n"
    b"\t\t</dict>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Day</key>\n"
    b"\t\t\t<integer>1</integer>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>9</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t\t<key>Month</key>\n"
    b"\t\t\t<integer>10</integer>\n"
    b"\t\t</dict>\n"
    b"\t</array>\n"
    b"\t<key>WorkingDirectory</key>\n"
    b"\t<string>/Users/user/vault</string>\n"
    b"</dict>\n"
    b"</plist>\n"
)


def test_render_quarterly_golden(emitter: LaunchdEmitter) -> None:
    """Quarterly cadence produces plist with four-element StartCalendarInterval array."""
    cadence = ResolvedCadence(period="quarterly", hour=9, minute=0, day_of_month=1)
    result = emitter.render_artifact(
        operation="quarterly-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=["/usr/local/bin/wiki", "run", "--exec", "quarterly-op"],
    )
    assert result == _QUARTERLY_DAY1_0900_GOLDEN


# ---------------------------------------------------------------------------
# 2. Quarterly StartCalendarInterval — four-element list with Month keys (1,4,7,10)
# ---------------------------------------------------------------------------


def test_quarterly_start_calendar_interval_four_elements(emitter: LaunchdEmitter) -> None:
    """Pins that the emitter hands the full ``to_launchd_calendar_interval``
    list to plistlib, not just ``intervals[0]``.

    Parsing the rendered bytes back through plistlib gives the authoritative
    view of what launchd will read.
    """
    cadence = ResolvedCadence(period="quarterly", hour=9, minute=0, day_of_month=1)
    result = emitter.render_artifact(
        operation="quarterly-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=["/usr/local/bin/wiki", "run", "--exec", "quarterly-op"],
    )
    parsed = plistlib.loads(result)
    intervals = parsed["StartCalendarInterval"]
    assert isinstance(intervals, list), "StartCalendarInterval must be a list (array), not a dict"
    assert len(intervals) == 4, f"expected 4 intervals for quarterly, got {len(intervals)}"
    months = [entry["Month"] for entry in intervals]
    assert months == [1, 4, 7, 10], f"expected months (1,4,7,10), got {months}"


# ---------------------------------------------------------------------------
# 3. ProgramArguments pins ``wiki run --exec <op>`` shape
# ---------------------------------------------------------------------------


def test_program_arguments_wiki_run_exec_shape(emitter: LaunchdEmitter) -> None:
    """ProgramArguments embeds ``wiki run --exec <op>`` exactly as supplied."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    exec_cmd = ["/usr/local/bin/wiki", "run", "--exec", "my-operation"]
    result = emitter.render_artifact(
        operation="my-operation",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=exec_cmd,
    )
    parsed = plistlib.loads(result)
    assert parsed["ProgramArguments"] == exec_cmd
    # Structural assertion: exactly ["<wiki>", "run", "--exec", "<op>"].
    assert parsed["ProgramArguments"][1] == "run"
    assert parsed["ProgramArguments"][2] == "--exec"
    assert parsed["ProgramArguments"][3] == "my-operation"


def test_program_arguments_preserves_binary_path(emitter: LaunchdEmitter) -> None:
    """The wiki binary path at index [0] is preserved verbatim."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    exec_cmd = ["/opt/homebrew/bin/wiki", "run", "--exec", "daily-task"]
    result = emitter.render_artifact(
        operation="daily-task",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=exec_cmd,
    )
    parsed = plistlib.loads(result)
    assert parsed["ProgramArguments"][0] == "/opt/homebrew/bin/wiki"


# ---------------------------------------------------------------------------
# 4. inspect() — four InspectResult states via subprocess monkeypatch
#
# Style convention (schedule/_emitter.py): monkeypatch ``subprocess.run``
# inside the emitter module, not globally.
# ---------------------------------------------------------------------------


def test_inspect_missing_file_when_artifact_absent(emitter: LaunchdEmitter, tmp_path: Path) -> None:
    """``"missing-file"`` when the plist file does not exist on disk."""
    absent = tmp_path / "com.llm-wiki-kit.aabbcc.nonexistent.plist"
    # Do not create the file.
    result = emitter.inspect(absent)
    assert result == "missing-file"


def test_inspect_loaded_when_launchctl_print_succeeds(
    emitter: LaunchdEmitter,
    artifact_file: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """``"loaded"`` when ``launchctl print`` exits 0."""

    def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        # Simulate a successful ``launchctl print gui/<uid>/<label>`` response.
        label = "com.llm-wiki-kit.abcdef123456.test-op"
        return subprocess.CompletedProcess(
            args=cmd,
            returncode=0,
            stdout=(
                "{\n"
                "\tactive count = 1\n"
                f"\tpath = /Users/user/Library/LaunchAgents/{label}.plist\n"
                "\tstate = waiting\n"
                "}\n"
            ),
            stderr="",
        )

    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.subprocess.run", mock_run)
    result = emitter.inspect(artifact_file)
    assert result == "loaded"


def test_inspect_not_loaded_when_launchctl_print_fails(
    emitter: LaunchdEmitter,
    artifact_file: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """``"not-loaded"`` when ``launchctl print`` exits non-zero.

    This covers the post-bootout state where the plist file is still on
    disk but launchd no longer has the service registered.
    """

    def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(
            args=cmd,
            returncode=113,
            stdout="",
            stderr="Could not find service "
            '"com.llm-wiki-kit.abcdef123456.test-op" in domain for port\n',
        )

    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.subprocess.run", mock_run)
    result = emitter.inspect(artifact_file)
    assert result == "not-loaded"


def test_inspect_not_loaded_covers_system_restart_state(
    emitter: LaunchdEmitter,
    artifact_file: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Non-zero from ``launchctl print`` maps to ``"not-loaded"`` regardless of message."""

    def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(
            args=cmd,
            returncode=1,
            stdout="",
            stderr="",
        )

    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.subprocess.run", mock_run)
    result = emitter.inspect(artifact_file)
    assert result == "not-loaded"


# ---------------------------------------------------------------------------
# Additional structural assertions
# ---------------------------------------------------------------------------


def test_artifact_path_shape(emitter: LaunchdEmitter) -> None:
    """artifact_path returns the canonical ~/Library/LaunchAgents/<label>.plist."""
    path = emitter.artifact_path("abc123def456", "weekly-digest")
    assert path.parent == Path.home() / "Library" / "LaunchAgents"
    assert path.name == "com.llm-wiki-kit.abc123def456.weekly-digest.plist"
    assert path.suffix == ".plist"


def test_render_artifact_returns_bytes(emitter: LaunchdEmitter) -> None:
    """render_artifact always returns bytes (Protocol return type is ``str | bytes``)."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    result = emitter.render_artifact(
        operation="daily-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=EXEC_CMD,
    )
    assert isinstance(result, bytes)


def test_render_includes_working_directory(emitter: LaunchdEmitter) -> None:
    """WorkingDirectory is set to the vault root (absolute path)."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    result = emitter.render_artifact(
        operation="daily-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=EXEC_CMD,
    )
    parsed = plistlib.loads(result)
    assert parsed["WorkingDirectory"] == str(VAULT_ROOT)


def test_render_log_paths_under_wiki_journal(emitter: LaunchdEmitter) -> None:
    """StandardOutPath and StandardErrorPath live under <vault-root>/.wiki.journal/exec-logs/."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    result = emitter.render_artifact(
        operation="daily-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=EXEC_CMD,
    )
    parsed = plistlib.loads(result)
    expected_prefix = str(VAULT_ROOT / ".wiki.journal" / "exec-logs")
    assert parsed["StandardOutPath"].startswith(expected_prefix)
    assert parsed["StandardErrorPath"].startswith(expected_prefix)
    assert parsed["StandardOutPath"].endswith("launchd-stdout.log")
    assert parsed["StandardErrorPath"].endswith("launchd-stderr.log")


def test_render_run_at_load_is_false(emitter: LaunchdEmitter) -> None:
    """RunAtLoad is always False — spec §'Artifact templates / launchd plist'."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    result = emitter.render_artifact(
        operation="daily-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=EXEC_CMD,
    )
    parsed = plistlib.loads(result)
    assert parsed["RunAtLoad"] is False
