"""Tests for ``llm_wiki_kit.schedule.launchd``.

Covers the four mandated cases from plan step 4 in
``docs/specs/wiki-schedule/plan.md``:

1. ``render_artifact()`` golden-string assertions for each cadence kind
   (daily / weekly / monthly / quarterly). The weekly golden string for
   ``TUE 18:00`` also pins spec CT-2's ``Weekday=2 Hour=18 Minute=0``
   encoding.
2. For a quarterly cadence, the rendered plist's ``StartCalendarInterval``
   is a four-element array of dicts whose ``Month`` keys are
   ``(1, 4, 7, 10)``. Pins that the emitter hands the full
   ``to_launchd_calendar_interval(...)`` list to ``plistlib``, not just
   ``intervals[0]``.
3. The argv-block contents pin ``wiki run --exec <op>`` shape in
   ``ProgramArguments``.
4. ``inspect()`` returns each of the four ``InspectResult`` states given
   fixture ``launchctl print`` outputs (mocked via subprocess monkeypatch
   of the ``llm_wiki_kit.schedule.launchd`` module, per the style
   convention in ``schedule/_emitter.py``).

Integration test (``@pytest.mark.slow``, Darwin-only) lives in
``tests/integration/test_schedule_launchd_macos.py``.
"""

from __future__ import annotations

import plistlib
import subprocess
from pathlib import Path

import pytest

from llm_wiki_kit.schedule.dsl import ResolvedCadence
from llm_wiki_kit.schedule.launchd import LaunchdEmitter

# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------

VAULT_ROOT = Path("/Users/user/vault")
VAULT_ID = "abcdef123456"
EXEC_CMD = ["/usr/local/bin/wiki", "run", "--exec", "test-op"]

# A stable artifact path fixture used by inspect() tests.
_ARTIFACT_NAME = f"com.llm-wiki-kit.{VAULT_ID}.test-op.plist"


@pytest.fixture
def emitter() -> LaunchdEmitter:
    return LaunchdEmitter()


@pytest.fixture
def artifact_file(tmp_path: Path) -> Path:
    """Create a real (empty) plist file so ``artifact_path.exists()`` is True."""
    p = tmp_path / _ARTIFACT_NAME
    p.touch()
    return p


# ---------------------------------------------------------------------------
# 1. Golden-string assertions per cadence kind
# ---------------------------------------------------------------------------

# The golden strings below were generated by running the emitter against the
# same inputs and capturing the exact bytes. plistlib uses sort_keys=True by
# default, so keys appear alphabetically inside each <dict>.

_DAILY_GOLDEN = (
    b'<?xml version="1.0" encoding="UTF-8"?>\n'
    b'<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"'
    b' "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    b'<plist version="1.0">\n'
    b"<dict>\n"
    b"\t<key>Label</key>\n"
    b"\t<string>com.llm-wiki-kit.abcdef123456.daily-op</string>\n"
    b"\t<key>ProgramArguments</key>\n"
    b"\t<array>\n"
    b"\t\t<string>/usr/local/bin/wiki</string>\n"
    b"\t\t<string>run</string>\n"
    b"\t\t<string>--exec</string>\n"
    b"\t\t<string>daily-op</string>\n"
    b"\t</array>\n"
    b"\t<key>RunAtLoad</key>\n"
    b"\t<false/>\n"
    b"\t<key>StandardErrorPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stderr.log</string>\n"
    b"\t<key>StandardOutPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stdout.log</string>\n"
    b"\t<key>StartCalendarInterval</key>\n"
    b"\t<array>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>7</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t</dict>\n"
    b"\t</array>\n"
    b"\t<key>WorkingDirectory</key>\n"
    b"\t<string>/Users/user/vault</string>\n"
    b"</dict>\n"
    b"</plist>\n"
)


def test_render_daily_golden(emitter: LaunchdEmitter) -> None:
    """Daily cadence produces the exact plist bytes pinned above."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    result = emitter.render_artifact(
        operation="daily-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=["/usr/local/bin/wiki", "run", "--exec", "daily-op"],
    )
    assert result == _DAILY_GOLDEN


# spec CT-2: TUE 18:00 → Weekday=2 Hour=18 Minute=0 (Sunday=0…Saturday=6).
_WEEKLY_TUE_1800_GOLDEN = (
    b'<?xml version="1.0" encoding="UTF-8"?>\n'
    b'<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"'
    b' "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    b'<plist version="1.0">\n'
    b"<dict>\n"
    b"\t<key>Label</key>\n"
    b"\t<string>com.llm-wiki-kit.abcdef123456.weekly-digest</string>\n"
    b"\t<key>ProgramArguments</key>\n"
    b"\t<array>\n"
    b"\t\t<string>/usr/local/bin/wiki</string>\n"
    b"\t\t<string>run</string>\n"
    b"\t\t<string>--exec</string>\n"
    b"\t\t<string>weekly-digest</string>\n"
    b"\t</array>\n"
    b"\t<key>RunAtLoad</key>\n"
    b"\t<false/>\n"
    b"\t<key>StandardErrorPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stderr.log</string>\n"
    b"\t<key>StandardOutPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stdout.log</string>\n"
    b"\t<key>StartCalendarInterval</key>\n"
    b"\t<array>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>18</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t\t<key>Weekday</key>\n"
    b"\t\t\t<integer>2</integer>\n"
    b"\t\t</dict>\n"
    b"\t</array>\n"
    b"\t<key>WorkingDirectory</key>\n"
    b"\t<string>/Users/user/vault</string>\n"
    b"</dict>\n"
    b"</plist>\n"
)


def test_render_weekly_tue_1800_golden(emitter: LaunchdEmitter) -> None:
    """Weekly TUE 18:00 produces plist with Weekday=2 Hour=18 Minute=0 (spec CT-2)."""
    cadence = ResolvedCadence(period="weekly", hour=18, minute=0, day_of_week=2)
    result = emitter.render_artifact(
        operation="weekly-digest",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=["/usr/local/bin/wiki", "run", "--exec", "weekly-digest"],
    )
    assert result == _WEEKLY_TUE_1800_GOLDEN


_MONTHLY_DAY5_0900_GOLDEN = (
    b'<?xml version="1.0" encoding="UTF-8"?>\n'
    b'<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"'
    b' "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    b'<plist version="1.0">\n'
    b"<dict>\n"
    b"\t<key>Label</key>\n"
    b"\t<string>com.llm-wiki-kit.abcdef123456.monthly-op</string>\n"
    b"\t<key>ProgramArguments</key>\n"
    b"\t<array>\n"
    b"\t\t<string>/usr/local/bin/wiki</string>\n"
    b"\t\t<string>run</string>\n"
    b"\t\t<string>--exec</string>\n"
    b"\t\t<string>monthly-op</string>\n"
    b"\t</array>\n"
    b"\t<key>RunAtLoad</key>\n"
    b"\t<false/>\n"
    b"\t<key>StandardErrorPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stderr.log</string>\n"
    b"\t<key>StandardOutPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stdout.log</string>\n"
    b"\t<key>StartCalendarInterval</key>\n"
    b"\t<array>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Day</key>\n"
    b"\t\t\t<integer>5</integer>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>9</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t</dict>\n"
    b"\t</array>\n"
    b"\t<key>WorkingDirectory</key>\n"
    b"\t<string>/Users/user/vault</string>\n"
    b"</dict>\n"
    b"</plist>\n"
)


def test_render_monthly_golden(emitter: LaunchdEmitter) -> None:
    """Monthly day-5 cadence produces the exact plist bytes pinned above."""
    cadence = ResolvedCadence(period="monthly", hour=9, minute=0, day_of_month=5)
    result = emitter.render_artifact(
        operation="monthly-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=["/usr/local/bin/wiki", "run", "--exec", "monthly-op"],
    )
    assert result == _MONTHLY_DAY5_0900_GOLDEN


_QUARTERLY_DAY1_0900_GOLDEN = (
    b'<?xml version="1.0" encoding="UTF-8"?>\n'
    b'<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"'
    b' "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    b'<plist version="1.0">\n'
    b"<dict>\n"
    b"\t<key>Label</key>\n"
    b"\t<string>com.llm-wiki-kit.abcdef123456.quarterly-op</string>\n"
    b"\t<key>ProgramArguments</key>\n"
    b"\t<array>\n"
    b"\t\t<string>/usr/local/bin/wiki</string>\n"
    b"\t\t<string>run</string>\n"
    b"\t\t<string>--exec</string>\n"
    b"\t\t<string>quarterly-op</string>\n"
    b"\t</array>\n"
    b"\t<key>RunAtLoad</key>\n"
    b"\t<false/>\n"
    b"\t<key>StandardErrorPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stderr.log</string>\n"
    b"\t<key>StandardOutPath</key>\n"
    b"\t<string>/Users/user/vault/.wiki.journal/exec-logs/launchd-stdout.log</string>\n"
    b"\t<key>StartCalendarInterval</key>\n"
    b"\t<array>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Day</key>\n"
    b"\t\t\t<integer>1</integer>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>9</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t\t<key>Month</key>\n"
    b"\t\t\t<integer>1</integer>\n"
    b"\t\t</dict>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Day</key>\n"
    b"\t\t\t<integer>1</integer>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>9</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t\t<key>Month</key>\n"
    b"\t\t\t<integer>4</integer>\n"
    b"\t\t</dict>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Day</key>\n"
    b"\t\t\t<integer>1</integer>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>9</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t\t<key>Month</key>\n"
    b"\t\t\t<integer>7</integer>\n"
    b"\t\t</dict>\n"
    b"\t\t<dict>\n"
    b"\t\t\t<key>Day</key>\n"
    b"\t\t\t<integer>1</integer>\n"
    b"\t\t\t<key>Hour</key>\n"
    b"\t\t\t<integer>9</integer>\n"
    b"\t\t\t<key>Minute</key>\n"
    b"\t\t\t<integer>0</integer>\n"
    b"\t\t\t<key>Month</key>\n"
    b"\t\t\t<integer>10</integer>\n"
    b"\t\t</dict>\n"
    b"\t</array>\n"
    b"\t<key>WorkingDirectory</key>\n"
    b"\t<string>/Users/user/vault</string>\n"
    b"</dict>\n"
    b"</plist>\n"
)


def test_render_quarterly_golden(emitter: LaunchdEmitter) -> None:
    """Quarterly cadence produces plist with four-element StartCalendarInterval array."""
    cadence = ResolvedCadence(period="quarterly", hour=9, minute=0, day_of_month=1)
    result = emitter.render_artifact(
        operation="quarterly-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=["/usr/local/bin/wiki", "run", "--exec", "quarterly-op"],
    )
    assert result == _QUARTERLY_DAY1_0900_GOLDEN


# ---------------------------------------------------------------------------
# 2. Quarterly StartCalendarInterval — four-element list with Month keys (1,4,7,10)
# ---------------------------------------------------------------------------


def test_quarterly_start_calendar_interval_four_elements(emitter: LaunchdEmitter) -> None:
    """Pins that the emitter hands the full ``to_launchd_calendar_interval``
    list to plistlib, not just ``intervals[0]``.

    Parsing the rendered bytes back through plistlib gives the authoritative
    view of what launchd will read.
    """
    cadence = ResolvedCadence(period="quarterly", hour=9, minute=0, day_of_month=1)
    result = emitter.render_artifact(
        operation="quarterly-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=["/usr/local/bin/wiki", "run", "--exec", "quarterly-op"],
    )
    parsed = plistlib.loads(result)
    intervals = parsed["StartCalendarInterval"]
    assert isinstance(intervals, list), "StartCalendarInterval must be a list (array), not a dict"
    assert len(intervals) == 4, f"expected 4 intervals for quarterly, got {len(intervals)}"
    months = [entry["Month"] for entry in intervals]
    assert months == [1, 4, 7, 10], f"expected months (1,4,7,10), got {months}"


# ---------------------------------------------------------------------------
# 3. ProgramArguments pins ``wiki run --exec <op>`` shape
# ---------------------------------------------------------------------------


def test_program_arguments_wiki_run_exec_shape(emitter: LaunchdEmitter) -> None:
    """ProgramArguments embeds ``wiki run --exec <op>`` exactly as supplied."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    exec_cmd = ["/usr/local/bin/wiki", "run", "--exec", "my-operation"]
    result = emitter.render_artifact(
        operation="my-operation",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=exec_cmd,
    )
    parsed = plistlib.loads(result)
    assert parsed["ProgramArguments"] == exec_cmd
    # Structural assertion: exactly ["<wiki>", "run", "--exec", "<op>"].
    assert parsed["ProgramArguments"][1] == "run"
    assert parsed["ProgramArguments"][2] == "--exec"
    assert parsed["ProgramArguments"][3] == "my-operation"


def test_program_arguments_preserves_binary_path(emitter: LaunchdEmitter) -> None:
    """The wiki binary path at index [0] is preserved verbatim."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    exec_cmd = ["/opt/homebrew/bin/wiki", "run", "--exec", "daily-task"]
    result = emitter.render_artifact(
        operation="daily-task",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=exec_cmd,
    )
    parsed = plistlib.loads(result)
    assert parsed["ProgramArguments"][0] == "/opt/homebrew/bin/wiki"


# ---------------------------------------------------------------------------
# 4. inspect() — four InspectResult states via subprocess monkeypatch
#
# Style convention (schedule/_emitter.py): monkeypatch ``subprocess.run``
# inside the emitter module, not globally.
# ---------------------------------------------------------------------------


def test_inspect_missing_file_when_artifact_absent(emitter: LaunchdEmitter, tmp_path: Path) -> None:
    """``"missing-file"`` when the plist file does not exist on disk."""
    absent = tmp_path / "com.llm-wiki-kit.aabbcc.nonexistent.plist"
    # Do not create the file.
    result = emitter.inspect(absent)
    assert result == "missing-file"


def test_inspect_loaded_when_launchctl_print_succeeds(
    emitter: LaunchdEmitter,
    artifact_file: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """``"loaded"`` when ``launchctl print`` exits 0."""

    def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        # Simulate a successful ``launchctl print gui/<uid>/<label>`` response.
        label = "com.llm-wiki-kit.abcdef123456.test-op"
        return subprocess.CompletedProcess(
            args=cmd,
            returncode=0,
            stdout=(
                "{\n"
                "\tactive count = 1\n"
                f"\tpath = /Users/user/Library/LaunchAgents/{label}.plist\n"
                "\tstate = waiting\n"
                "}\n"
            ),
            stderr="",
        )

    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.subprocess.run", mock_run)
    result = emitter.inspect(artifact_file)
    assert result == "loaded"


@pytest.mark.parametrize(
    "returncode,stderr",
    [
        (
            113,
            'Could not find service "com.llm-wiki-kit.abcdef123456.test-op" in domain for port\n',
        ),
        (1, ""),
    ],
    ids=["post-bootout-exit-113", "system-restart-exit-1"],
)
def test_inspect_not_loaded_when_launchctl_print_fails(
    returncode: int,
    stderr: str,
    emitter: LaunchdEmitter,
    artifact_file: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """``"not-loaded"`` when ``launchctl print`` exits non-zero, regardless of message."""

    def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(
            args=cmd,
            returncode=returncode,
            stdout="",
            stderr=stderr,
        )

    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.subprocess.run", mock_run)
    result = emitter.inspect(artifact_file)
    assert result == "not-loaded"


# ---------------------------------------------------------------------------
# Additional structural assertions
# ---------------------------------------------------------------------------


def test_artifact_path_shape(emitter: LaunchdEmitter) -> None:
    """artifact_path returns the canonical ~/Library/LaunchAgents/<label>.plist."""
    path = emitter.artifact_path("abc123def456", "weekly-digest")
    assert path.parent == Path.home() / "Library" / "LaunchAgents"
    assert path.name == "com.llm-wiki-kit.abc123def456.weekly-digest.plist"
    assert path.suffix == ".plist"


def test_launchd_chooses_bytes_for_plistlib_xml(emitter: LaunchdEmitter) -> None:
    """Launchd renders via ``plistlib.dumps(FMT_XML)``, which returns bytes.

    The ``str | bytes`` Protocol slot is satisfied by the bytes branch.
    """
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    result = emitter.render_artifact(
        operation="daily-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=EXEC_CMD,
    )
    assert isinstance(result, bytes)


def test_render_includes_working_directory(emitter: LaunchdEmitter) -> None:
    """WorkingDirectory is set to the vault root (absolute path)."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    result = emitter.render_artifact(
        operation="daily-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=EXEC_CMD,
    )
    parsed = plistlib.loads(result)
    assert parsed["WorkingDirectory"] == str(VAULT_ROOT)


def test_render_log_paths_under_wiki_journal(emitter: LaunchdEmitter) -> None:
    """StandardOutPath and StandardErrorPath live under <vault-root>/.wiki.journal/exec-logs/."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    result = emitter.render_artifact(
        operation="daily-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=EXEC_CMD,
    )
    parsed = plistlib.loads(result)
    expected_prefix = str(VAULT_ROOT / ".wiki.journal" / "exec-logs")
    assert parsed["StandardOutPath"].startswith(expected_prefix)
    assert parsed["StandardErrorPath"].startswith(expected_prefix)
    assert parsed["StandardOutPath"].endswith("launchd-stdout.log")
    assert parsed["StandardErrorPath"].endswith("launchd-stderr.log")


def test_render_run_at_load_is_false(emitter: LaunchdEmitter) -> None:
    """RunAtLoad is always False — spec §'Artifact templates / launchd plist'."""
    cadence = ResolvedCadence(period="daily", hour=7, minute=0)
    result = emitter.render_artifact(
        operation="daily-op",
        vault_root=VAULT_ROOT,
        vault_id=VAULT_ID,
        cadence=cadence,
        exec_command=EXEC_CMD,
    )
    parsed = plistlib.loads(result)
    assert parsed["RunAtLoad"] is False


def test_inspect_raises_wiki_error_for_non_plist_suffix(
    emitter: LaunchdEmitter, tmp_path: Path
) -> None:
    """``inspect()`` raises ``WikiError`` immediately when given a non-``.plist`` path.

    The label is derived from ``artifact_path.stem``, so a wrong suffix
    (e.g. ``.xml``, no extension) would silently mis-derive the label.
    The assertion guards against that before any filesystem or subprocess call.
    """
    from llm_wiki_kit.errors import WikiError

    bad_path = tmp_path / "com.llm-wiki-kit.abc123.my-op.xml"
    with pytest.raises(WikiError, match=r"\.plist"):
        emitter.inspect(bad_path)


# ---------------------------------------------------------------------------
# activate() — WikiError message golden for the failure path
# ---------------------------------------------------------------------------


def test_activate_raises_wiki_error_with_exit_code(
    emitter: LaunchdEmitter,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """``activate()`` raises ``WikiError`` whose message contains ``(exit code N):`` and stderr.

    The exit code is operationally critical: users cross-reference it
    against launchctl docs.  The message also includes the OS verb
    (``launchctl bootstrap``), the artifact path, and the stderr text.
    """
    from llm_wiki_kit.errors import WikiError

    plist_path = tmp_path / "com.llm-wiki-kit.abc123.my-op.plist"

    def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(
            args=cmd,
            returncode=17,
            stdout="",
            stderr="Load failed: 17: File exists",
        )

    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.subprocess.run", mock_run)

    with pytest.raises(WikiError) as exc_info:
        emitter.activate(plist_path)

    msg = str(exc_info.value)
    assert "launchctl bootstrap" in msg
    assert str(plist_path) in msg
    assert "(exit code 17):" in msg
    assert "Load failed: 17: File exists" in msg


def test_activate_raises_wiki_error_with_no_stderr_fallback(
    emitter: LaunchdEmitter,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """When stderr is empty ``activate()`` substitutes ``<no stderr>`` in the message."""
    from llm_wiki_kit.errors import WikiError

    plist_path = tmp_path / "com.llm-wiki-kit.abc123.my-op.plist"

    def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(
            args=cmd,
            returncode=1,
            stdout="",
            stderr="",
        )

    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.subprocess.run", mock_run)

    with pytest.raises(WikiError) as exc_info:
        emitter.activate(plist_path)

    msg = str(exc_info.value)
    assert "(exit code 1):" in msg
    assert "<no stderr>" in msg


# ---------------------------------------------------------------------------
# C1. Timeout handling — all three subprocess.run calls
# ---------------------------------------------------------------------------


def test_activate_raises_wiki_error_on_timeout(
    emitter: LaunchdEmitter,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """``activate()`` raises ``WikiError`` whose message mentions 'timed out' on timeout."""
    from llm_wiki_kit.errors import WikiError

    plist_path = tmp_path / "com.llm-wiki-kit.abc123.my-op.plist"

    def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        raise subprocess.TimeoutExpired(cmd=cmd, timeout=10.0)

    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.subprocess.run", mock_run)

    with pytest.raises(WikiError) as exc_info:
        emitter.activate(plist_path)

    msg = str(exc_info.value)
    assert "launchctl bootstrap" in msg
    assert str(plist_path) in msg
    assert "timed out" in msg


def test_deactivate_logs_but_does_not_raise_on_timeout(
    emitter: LaunchdEmitter,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """``deactivate()`` logs to stderr but does not raise on timeout."""
    plist_path = tmp_path / "com.llm-wiki-kit.abc123.my-op.plist"

    def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        raise subprocess.TimeoutExpired(cmd=cmd, timeout=10.0)

    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.subprocess.run", mock_run)

    emitter.deactivate(plist_path)  # must not raise

    captured = capsys.readouterr()
    assert "wiki schedule: warning:" in captured.err
    assert "launchctl bootout" in captured.err
    assert str(plist_path) in captured.err


def test_inspect_returns_not_loaded_on_timeout(
    emitter: LaunchdEmitter,
    artifact_file: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """``inspect()`` returns ``"not-loaded"`` when ``launchctl print`` times out."""

    def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        raise subprocess.TimeoutExpired(cmd=cmd, timeout=10.0)

    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.subprocess.run", mock_run)
    result = emitter.inspect(artifact_file)
    assert result == "not-loaded"


# ---------------------------------------------------------------------------
# C2. deactivate() non-zero path — logs stderr, does not raise
# ---------------------------------------------------------------------------


def test_deactivate_logs_but_does_not_raise_on_nonzero(
    emitter: LaunchdEmitter,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """``deactivate()`` logs to stderr but does not raise on non-zero exit.

    The orchestrator (PR-5) relies on this contract — uninstall intent is
    always recorded in the journal regardless of launchctl exit code.
    """
    plist_path = tmp_path / "com.llm-wiki-kit.abc123.my-op.plist"

    def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(
            args=cmd,
            returncode=1,
            stdout="",
            stderr="bootout failure",
        )

    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.subprocess.run", mock_run)

    emitter.deactivate(plist_path)  # must not raise

    captured = capsys.readouterr()
    assert "wiki schedule: warning:" in captured.err
    assert "launchctl bootout" in captured.err
    assert str(plist_path) in captured.err


# ---------------------------------------------------------------------------
# C3. inspect() never returns "not-inspectable"
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "returncode,stdout,stderr,raises_timeout",
    [
        (0, "active count = 1\n", "", False),
        (113, "", "Could not find service\n", False),
        (1, "", "", False),
        (0, "", "", True),  # timeout branch — raises_timeout=True
    ],
    ids=["loaded", "not-loaded-exit-113", "not-loaded-exit-1", "timeout"],
)
def test_inspect_never_returns_not_inspectable(
    returncode: int,
    stdout: str,
    stderr: str,
    raises_timeout: bool,
    emitter: LaunchdEmitter,
    artifact_file: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """``inspect()`` always returns one of the three macOS-reachable states.

    ``"not-inspectable"`` is the Windows v1 fallback and must never appear
    from this implementation.
    """
    valid_results = {"loaded", "not-loaded", "missing-file"}

    if raises_timeout:

        def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
            raise subprocess.TimeoutExpired(cmd=cmd, timeout=10.0)

    else:

        def mock_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=returncode,
                stdout=stdout,
                stderr=stderr,
            )

    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.subprocess.run", mock_run)
    result = emitter.inspect(artifact_file)
    assert result in valid_results, f"inspect() returned unexpected {result!r}"


# ---------------------------------------------------------------------------
# disabled_hint — surfaced by ``wiki doctor`` when inspect() == "not-loaded"
# ---------------------------------------------------------------------------


def test_disabled_hint_names_launchctl_bootstrap_for_current_uid(
    emitter: LaunchdEmitter, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``disabled_hint`` returns the exact ``launchctl bootstrap gui/<uid>`` line.

    Pinned with a fixture UID so the assertion doesn't depend on the
    runner's actual UID. Doctor's ``schedule-disabled`` warning embeds
    this string verbatim; a templating drift here would silently mangle
    the hint without breaking the doctor substring assertion (which
    only checks ``"launchctl bootstrap"`` presence).
    """
    monkeypatch.setattr("llm_wiki_kit.schedule.launchd.os.getuid", lambda: 501)
    plist_path = Path("/Users/u/Library/LaunchAgents/com.llm-wiki-kit.x.op.plist")
    assert emitter.disabled_hint(plist_path) == (
        "launchctl bootstrap gui/501 /Users/u/Library/LaunchAgents/com.llm-wiki-kit.x.op.plist"
    )
